# Docs
#   https://docs.fastlane.tools
# Available actions
#   https://docs.fastlane.tools/actions

default_platform :ios
skip_docs

def version_code
  commit_count = sh('git rev-list --count master')
  Integer(commit_count) + 0
end

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :build do
    build_app
  end

  lane :build_ci do
    match type: 'appstore'
    increment_build_number build_number: version_code
    build_app
  end

  lane :beta_ci do
    changelog = changelog_from_git_commits
    upload_to_testflight changelog: changelog
  end

  lane :deploy_ci do
    puts 'TODO'
  end
end
