# Docs
#   https://docs.fastlane.tools
# Available actions
#   https://docs.fastlane.tools/actions

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :build do
    build_app
  end

  lane :build_ci do
    match type: 'appstore'
    build_number = sh('git rev-list --all --count')
    increment_build_number build_number: build_number
    build_app
  end

  desc 'Deploy beta version from CI to Testflight'
  lane :beta_ci do
    puts 'TODO'
  end

  desc 'Deploy production version from CI to App store'
  lane :deploy_ci do
    puts 'TODO'
  end
end
