window.esdocSearchIndex = [
  [
    "siding/src/utils/urls.js~base_url",
    "variable/index.html#static-variable-BASE_URL",
    "<span>BASE_URL</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/urls.js~courses_url",
    "variable/index.html#static-variable-COURSES_URL",
    "<span>COURSES_URL</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/urls.js~current_courses_url",
    "variable/index.html#static-variable-CURRENT_COURSES_URL",
    "<span>CURRENT_COURSES_URL</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/date.js~current_date",
    "variable/index.html#static-variable-CURRENT_DATE",
    "<span>CURRENT_DATE</span> <span class=\"search-result-import-path\">siding/src/utils/date.js</span>",
    "variable"
  ],
  [
    "siding/src/components/course.js~course",
    "function/index.html#static-function-Course",
    "<span>Course</span> <span class=\"search-result-import-path\">siding/src/components/Course.js</span>",
    "function"
  ],
  [
    "siding/src/components/courseslist.js~courseslist",
    "class/src/components/CoursesList.js~CoursesList.html",
    "<span>CoursesList</span> <span class=\"search-result-import-path\">siding/src/components/CoursesList.js</span>",
    "class"
  ],
  [
    "siding/src/redux/modules/courses.js~load_courses",
    "variable/index.html#static-variable-LOAD_COURSES",
    "<span>LOAD_COURSES</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/courses.js~load_courses_fulfilled",
    "variable/index.html#static-variable-LOAD_COURSES_FULFILLED",
    "<span>LOAD_COURSES_FULFILLED</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/courses.js~load_courses_pending",
    "variable/index.html#static-variable-LOAD_COURSES_PENDING",
    "<span>LOAD_COURSES_PENDING</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/courses.js~load_courses_rejected",
    "variable/index.html#static-variable-LOAD_COURSES_REJECTED",
    "<span>LOAD_COURSES_REJECTED</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~login",
    "variable/index.html#static-variable-LOGIN",
    "<span>LOGIN</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~login_fulfilled",
    "variable/index.html#static-variable-LOGIN_FULFILLED",
    "<span>LOGIN_FULFILLED</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~login_pending",
    "variable/index.html#static-variable-LOGIN_PENDING",
    "<span>LOGIN_PENDING</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~login_rejected",
    "variable/index.html#static-variable-LOGIN_REJECTED",
    "<span>LOGIN_REJECTED</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/urls.js~login_url",
    "variable/index.html#static-variable-LOGIN_URL",
    "<span>LOGIN_URL</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/urls.js~logout_url",
    "variable/index.html#static-variable-LOGOUT_URL",
    "<span>LOGOUT_URL</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "variable"
  ],
  [
    "siding/src/components/loadingview.js~loadingview",
    "function/index.html#static-function-LoadingView",
    "<span>LoadingView</span> <span class=\"search-result-import-path\">siding/src/components/LoadingView.js</span>",
    "function"
  ],
  [
    "siding/src/router.js~router",
    "function/index.html#static-function-Router",
    "<span>Router</span> <span class=\"search-result-import-path\">siding/src/Router.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~siding_auth_failed",
    "variable/index.html#static-variable-SIDING_AUTH_FAILED",
    "<span>SIDING_AUTH_FAILED</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/date.js~siding_semester",
    "variable/index.html#static-variable-SIDING_SEMESTER",
    "<span>SIDING_SEMESTER</span> <span class=\"search-result-import-path\">siding/src/utils/date.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/date.js~siding_year",
    "variable/index.html#static-variable-SIDING_YEAR",
    "<span>SIDING_YEAR</span> <span class=\"search-result-import-path\">siding/src/utils/date.js</span>",
    "variable"
  ],
  [
    "siding/src/containers/sessiongate.js~sessiongate",
    "class/src/containers/SessionGate.js~SessionGate.html",
    "<span>SessionGate</span> <span class=\"search-result-import-path\">siding/src/containers/SessionGate.js</span>",
    "class"
  ],
  [
    "siding/src/siding.js~siding",
    "function/index.html#static-function-Siding",
    "<span>Siding</span> <span class=\"search-result-import-path\">siding/src/Siding.js</span>",
    "function"
  ],
  [
    "siding/src/utils/wait.js~wait_seconds",
    "variable/index.html#static-variable-WAIT_SECONDS",
    "<span>WAIT_SECONDS</span> <span class=\"search-result-import-path\">siding/src/utils/wait.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/api.js~auth",
    "function/index.html#static-function-auth",
    "<span>auth</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~authorizedget",
    "function/index.html#static-function-authorizedGet",
    "<span>authorizedGet</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~authorizedpost",
    "function/index.html#static-function-authorizedPost",
    "<span>authorizedPost</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/routes.js~buildurl",
    "function/index.html#static-function-buildUrl",
    "<span>buildUrl</span> <span class=\"search-result-import-path\">siding/src/routes.js</span>",
    "function"
  ],
  [
    "siding/src/redux/schemas.js~courseschema",
    "variable/index.html#static-variable-courseSchema",
    "<span>courseSchema</span> <span class=\"search-result-import-path\">siding/src/redux/schemas.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/urls.js~courseurl",
    "function/index.html#static-function-courseUrl",
    "<span>courseUrl</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "function"
  ],
  [
    "siding/src/utils/urls.js~coursescatalogurl",
    "function/index.html#static-function-coursesCatalogUrl",
    "<span>coursesCatalogUrl</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "function"
  ],
  [
    "siding/src/utils/urls.js~coursesurl",
    "function/index.html#static-function-coursesUrl",
    "<span>coursesUrl</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "function"
  ],
  [
    "siding/src/redux/schemas.js~fileschema",
    "variable/index.html#static-variable-fileSchema",
    "<span>fileSchema</span> <span class=\"search-result-import-path\">siding/src/redux/schemas.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/schemas.js~folderschema",
    "variable/index.html#static-variable-folderSchema",
    "<span>folderSchema</span> <span class=\"search-result-import-path\">siding/src/redux/schemas.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/urls.js~folderurl",
    "function/index.html#static-function-folderUrl",
    "<span>folderUrl</span> <span class=\"search-result-import-path\">siding/src/utils/urls.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~formdata",
    "function/index.html#static-function-formData",
    "<span>formData</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~get",
    "function/index.html#static-function-get",
    "<span>get</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/courses.js~getcoursesdate",
    "function/index.html#static-function-getCoursesDate",
    "<span>getCoursesDate</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/courses.js~getcoursesdatelist",
    "variable/index.html#static-variable-getCoursesDateList",
    "<span>getCoursesDateList</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/courses.js~getcoursesstate",
    "function/index.html#static-function-getCoursesState",
    "<span>getCoursesState</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/entities.js~getentities",
    "function/index.html#static-function-getEntities",
    "<span>getEntities</span> <span class=\"search-result-import-path\">siding/src/redux/modules/entities.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/user.js~getuser",
    "function/index.html#static-function-getUser",
    "<span>getUser</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/user.js~getuserauth",
    "variable/index.html#static-variable-getUserAuth",
    "<span>getUserAuth</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~getuserdata",
    "variable/index.html#static-variable-getUserData",
    "<span>getUserData</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~getusererror",
    "variable/index.html#static-variable-getUserError",
    "<span>getUserError</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~getuserloading",
    "variable/index.html#static-variable-getUserLoading",
    "<span>getUserLoading</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/user.js~getusername",
    "variable/index.html#static-variable-getUsername",
    "<span>getUsername</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "variable"
  ],
  [
    "siding/src/redux/modules/routes.js~goto",
    "function/index.html#static-function-goTo",
    "<span>goTo</span> <span class=\"search-result-import-path\">siding/src/redux/modules/routes.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/routes.js~gotocourse",
    "function/index.html#static-function-goToCourse",
    "<span>goToCourse</span> <span class=\"search-result-import-path\">siding/src/redux/modules/routes.js</span>",
    "function"
  ],
  [
    "siding/src/redux/store.js~history",
    "variable/index.html#static-variable-history",
    "<span>history</span> <span class=\"search-result-import-path\">siding/src/redux/store.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/api.js~loadcourse",
    "function/index.html#static-function-loadCourse",
    "<span>loadCourse</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/courses.js~loadcourses",
    "function/index.html#static-function-loadCourses",
    "<span>loadCourses</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~loadcourses",
    "function/index.html#static-function-loadCourses",
    "<span>loadCourses</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~loadfolder",
    "function/index.html#static-function-loadFolder",
    "<span>loadFolder</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/user.js~login",
    "function/index.html#static-function-login",
    "<span>login</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "function"
  ],
  [
    "siding/src/utils/api.js~logout",
    "function/index.html#static-function-logout",
    "<span>logout</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/config/colors.js~maincolor",
    "variable/index.html#static-variable-mainColor",
    "<span>mainColor</span> <span class=\"search-result-import-path\">siding/src/config/colors.js</span>",
    "variable"
  ],
  [
    "siding/src/config/colors.js~maincoloralternate",
    "variable/index.html#static-variable-mainColorAlternate",
    "<span>mainColorAlternate</span> <span class=\"search-result-import-path\">siding/src/config/colors.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/parser.js~parsecourse",
    "function/index.html#static-function-parseCourse",
    "<span>parseCourse</span> <span class=\"search-result-import-path\">siding/src/utils/parser.js</span>",
    "function"
  ],
  [
    "siding/src/utils/parser.js~parsecourses",
    "function/index.html#static-function-parseCourses",
    "<span>parseCourses</span> <span class=\"search-result-import-path\">siding/src/utils/parser.js</span>",
    "function"
  ],
  [
    "siding/src/utils/parser.js~parsefolder",
    "function/index.html#static-function-parseFolder",
    "<span>parseFolder</span> <span class=\"search-result-import-path\">siding/src/utils/parser.js</span>",
    "function"
  ],
  [
    "siding/src/redux/store.js~persistor",
    "variable/index.html#static-variable-persistor",
    "<span>persistor</span> <span class=\"search-result-import-path\">siding/src/redux/store.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/api.js~post",
    "function/index.html#static-function-post",
    "<span>post</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/courses.js~reducer",
    "function/index.html#static-function-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">siding/src/redux/modules/courses.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/entities.js~reducer",
    "function/index.html#static-function-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">siding/src/redux/modules/entities.js</span>",
    "function"
  ],
  [
    "siding/src/redux/modules/user.js~reducer",
    "function/index.html#static-function-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">siding/src/redux/modules/user.js</span>",
    "function"
  ],
  [
    "siding/src/redux/reducers.js~reducers",
    "variable/index.html#static-variable-reducers",
    "<span>reducers</span> <span class=\"search-result-import-path\">siding/src/redux/reducers.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/api.js~request",
    "function/index.html#static-function-request",
    "<span>request</span> <span class=\"search-result-import-path\">siding/src/utils/api.js</span>",
    "function"
  ],
  [
    "siding/src/routes.js~routenametolocation",
    "function/index.html#static-function-routeNameToLocation",
    "<span>routeNameToLocation</span> <span class=\"search-result-import-path\">siding/src/routes.js</span>",
    "function"
  ],
  [
    "siding/src/routes.js~routenametopath",
    "function/index.html#static-function-routeNameToPath",
    "<span>routeNameToPath</span> <span class=\"search-result-import-path\">siding/src/routes.js</span>",
    "function"
  ],
  [
    "siding/src/routes.js~routenames",
    "variable/index.html#static-variable-routeNames",
    "<span>routeNames</span> <span class=\"search-result-import-path\">siding/src/routes.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/date.js~sidingdateid",
    "function/index.html#static-function-sidingDateId",
    "<span>sidingDateId</span> <span class=\"search-result-import-path\">siding/src/utils/date.js</span>",
    "function"
  ],
  [
    "siding/src/utils/date.js~sidingdateidhuman",
    "function/index.html#static-function-sidingDateIdHuman",
    "<span>sidingDateIdHuman</span> <span class=\"search-result-import-path\">siding/src/utils/date.js</span>",
    "function"
  ],
  [
    "siding/src/utils/date.js~sidingsemester",
    "function/index.html#static-function-sidingSemester",
    "<span>sidingSemester</span> <span class=\"search-result-import-path\">siding/src/utils/date.js</span>",
    "function"
  ],
  [
    "siding/src/redux/store.js~store",
    "variable/index.html#static-variable-store",
    "<span>store</span> <span class=\"search-result-import-path\">siding/src/redux/store.js</span>",
    "variable"
  ],
  [
    "siding/src/utils/wait.js~wait",
    "function/index.html#static-function-wait",
    "<span>wait</span> <span class=\"search-result-import-path\">siding/src/utils/wait.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/router.js",
    "file/src/Router.js.html",
    "src/Router.js",
    "file"
  ],
  [
    "src/siding.js",
    "file/src/Siding.js.html",
    "src/Siding.js",
    "file"
  ],
  [
    "src/components/course.js",
    "file/src/components/Course.js.html",
    "src/components/Course.js",
    "file"
  ],
  [
    "src/components/courseslist.js",
    "file/src/components/CoursesList.js.html",
    "src/components/CoursesList.js",
    "file"
  ],
  [
    "src/components/courseslist.js~courseslist#componentdidupdate",
    "class/src/components/CoursesList.js~CoursesList.html#instance-method-componentDidUpdate",
    "src/components/CoursesList.js~CoursesList#componentDidUpdate",
    "method"
  ],
  [
    "src/components/courseslist.js~courseslist#render",
    "class/src/components/CoursesList.js~CoursesList.html#instance-method-render",
    "src/components/CoursesList.js~CoursesList#render",
    "method"
  ],
  [
    "src/components/courseslist.js~courseslist#rendercourse",
    "class/src/components/CoursesList.js~CoursesList.html#instance-member-renderCourse",
    "src/components/CoursesList.js~CoursesList#renderCourse",
    "member"
  ],
  [
    "src/components/loadingview.js",
    "file/src/components/LoadingView.js.html",
    "src/components/LoadingView.js",
    "file"
  ],
  [
    "src/config/colors.js",
    "file/src/config/colors.js.html",
    "src/config/colors.js",
    "file"
  ],
  [
    "src/containers/currentcourses.js",
    "file/src/containers/CurrentCourses.js.html",
    "src/containers/CurrentCourses.js",
    "file"
  ],
  [
    "src/containers/sessiongate.js",
    "file/src/containers/SessionGate.js.html",
    "src/containers/SessionGate.js",
    "file"
  ],
  [
    "src/containers/sessiongate.js~sessiongate#componentdidmount",
    "class/src/containers/SessionGate.js~SessionGate.html#instance-method-componentDidMount",
    "src/containers/SessionGate.js~SessionGate#componentDidMount",
    "method"
  ],
  [
    "src/containers/sessiongate.js~sessiongate#componentdidupdate",
    "class/src/containers/SessionGate.js~SessionGate.html#instance-method-componentDidUpdate",
    "src/containers/SessionGate.js~SessionGate#componentDidUpdate",
    "method"
  ],
  [
    "src/containers/sessiongate.js~sessiongate#constructor",
    "class/src/containers/SessionGate.js~SessionGate.html#instance-constructor-constructor",
    "src/containers/SessionGate.js~SessionGate#constructor",
    "method"
  ],
  [
    "src/containers/sessiongate.js~sessiongate#login",
    "class/src/containers/SessionGate.js~SessionGate.html#instance-member-login",
    "src/containers/SessionGate.js~SessionGate#login",
    "member"
  ],
  [
    "src/containers/sessiongate.js~sessiongate#render",
    "class/src/containers/SessionGate.js~SessionGate.html#instance-method-render",
    "src/containers/SessionGate.js~SessionGate#render",
    "method"
  ],
  [
    "src/containers/sessiongate.js~sessiongate#state",
    "class/src/containers/SessionGate.js~SessionGate.html#instance-member-state",
    "src/containers/SessionGate.js~SessionGate#state",
    "member"
  ],
  [
    "src/redux/modules/courses.js",
    "file/src/redux/modules/courses.js.html",
    "src/redux/modules/courses.js",
    "file"
  ],
  [
    "src/redux/modules/entities.js",
    "file/src/redux/modules/entities.js.html",
    "src/redux/modules/entities.js",
    "file"
  ],
  [
    "src/redux/modules/routes.js",
    "file/src/redux/modules/routes.js.html",
    "src/redux/modules/routes.js",
    "file"
  ],
  [
    "src/redux/modules/user.js",
    "file/src/redux/modules/user.js.html",
    "src/redux/modules/user.js",
    "file"
  ],
  [
    "src/redux/reducers.js",
    "file/src/redux/reducers.js.html",
    "src/redux/reducers.js",
    "file"
  ],
  [
    "src/redux/schemas.js",
    "file/src/redux/schemas.js.html",
    "src/redux/schemas.js",
    "file"
  ],
  [
    "src/redux/store.js",
    "file/src/redux/store.js.html",
    "src/redux/store.js",
    "file"
  ],
  [
    "src/routes.js",
    "file/src/routes.js.html",
    "src/routes.js",
    "file"
  ],
  [
    "src/utils/api.js",
    "file/src/utils/api.js.html",
    "src/utils/api.js",
    "file"
  ],
  [
    "src/utils/date.js",
    "file/src/utils/date.js.html",
    "src/utils/date.js",
    "file"
  ],
  [
    "src/utils/parser.js",
    "file/src/utils/parser.js.html",
    "src/utils/parser.js",
    "file"
  ],
  [
    "src/utils/urls.js",
    "file/src/utils/urls.js.html",
    "src/utils/urls.js",
    "file"
  ],
  [
    "src/utils/wait.js",
    "file/src/utils/wait.js.html",
    "src/utils/wait.js",
    "file"
  ]
]