# Docs
#   https://docs.fastlane.tools
# Available actions
#   https://docs.fastlane.tools/actions

default_platform :android
skip_docs

def version_code
  commit_count = sh('git rev-list --count master')
  Integer(commit_count) + 0
end

platform :android do
  lane :build do
    gradle task: 'clean assembleRelease'
  end

  lane :build_ci do
    file_path = '../app/build.gradle'
    text = File.read(file_path)
    replace = text.gsub(/versionCode \d+/, "versionCode #{version_code}")
    File.open(file_path, 'w') { |file| file.puts replace }
    gradle task: 'clean assembleRelease'
  end

  lane :deploy do
    gradle task: 'clean assembleRelease'
    upload_to_play_store
  end

  lane :beta_ci do
    changelog_from_git_commits
    upload_to_play_store(
      track: 'beta',
      apk: 'app/build/outputs/apk/app-release.apk'
    )
  end

  lane :deploy_ci do
    upload_to_play_store(
      track: 'production',
      apk: 'app/build/outputs/apk/app-release.apk'
    )
  end
end
